def pattern_count(text, pattern):
    count = 0
    for i in range(len(text) - len(pattern)):
        if text[i:i + len(pattern)] == pattern:
            count += 1
    
    return count


def print_results(text, pattern, expected, result):
    print("="*100)
    print(f"Text: {text}; Pattern: {pattern}")
    print(f"Expected: {expected}; Result: {result}")
    print("="*100)


if __name__ == "__main__":
    text_1 = "ACAACTATGCATACTATCGGGGACTATCCT"
    pattern_1 = "ACTAT"
    expected_1 = 3
    result_1 = pattern_count(text_1, pattern_1)

    print_results(text_1, pattern_1, expected_1, result_1)

    text_2 = "CGATATATCCATAG"
    pattern_2 = "ATA"
    expected_2 = 3
    result_2 = pattern_count(text_2, pattern_2)

    print_results(text_2, pattern_2, expected_2, result_2)

    text_3 = "TCGGGCCGGGATGGGCCGGGGGCCGGGCGGCCGGGGGGCCGGGCTCGGCCGGGCGAATTGGGTTGGGCCGGGGGCCGGGCAATGGCCGGGTGGGCCGGGGGCCGGGAGCTGGCCGGGAGGGGCCGGGTATAGTGGCGGGCCGGGGTGGCCGGGCAGGGCCGGGGGCCGGGGGCCGGGGAGGGCCGGGTTGCGATAGACGGGCCGGGACAGGCCGGGGAACGGCCGGGGGCCGGGTGAGGCCGGGGGCCGGGATTGGGGTATGGCCGGGTGGCCGGGGGCCGGGGGCCGGGGGCCGGGGGCCGGGACTGGGCCGGGCGGCCGGGCGGGCCGGGAAATCGGCCGGGGCGGCCGGGGGCCGGGATATGGCCGGGATGGGCCGGGTAGGGCCGGGGTCGCGAGAGGCCGGGGGCCGGGGGCCGGGCTTTGGGCCGGGGGCCGGGGAGGCCGGGAGGCCGGGGGCCGGGCGGCCGGGAGGCCGGGTAGGCCGGGTGGCCGGGGAAACCTCTAGGCCGGGTCGGCCGGGAAAACGGCCGGGGGCCGGGGGCTGAAGGCCGGGATAGGCCGGGGACCGGCACCGGCCGGGCGGCCGGGGGCCGGGGGCCGGGATGGCCGGGAGGGCCGGGCGGCCGGGGGCCGGGGGGCCGGGGGCCGGGGGCCGGGGGCCGGGTGCGAGATGGGGGCCGGGAGGCCGGGCACGGCCGGGAGGCCGGGAGGGCCGGGCCTCAGCGGCCGGGGAGGCCGGGCAGTCAACGGCCGGGTTGGCCGGGGGCCGGGGGCCGGGGGCCGGGGTGGCCGGGGGCCGGGTCCACCAGGCCGGGCGGCCGGGGGCCGGGGGCCGGGCACCGAGGCCGGGGGCCGGGGGCCGGGTGGTAGGCCGGGTCTTCTGGGCCGGGGGCCGGGGGGCCGGGGGCCGGGTCCGGGCCGGGAGGCCGGGCAGGCCGGGGGCCGGGAAGGCCGGGGCGGGGCCGGGGGTT"
    pattern_3 = "GGCCGGGGG"
    result_3 = pattern_count(text_3, pattern_3)
    
    print(result_3)